name: .NET Build and Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: "9.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4

    - name: 🛠 Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 🧠 Debug: folder structure
      run: ls -R

    - name: 📦 Restore dependencies
      run: dotnet restore DevHabit.sln

    - name: 🧱 Build
      run: dotnet build DevHabit.sln --configuration Release --no-restore

    - name: ✅ Test
      run: dotnet test DevHabit.sln --configuration Release --no-restore --no-build --logger trx --results-directory ./TestResults

    - name: 📤 Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./TestResults

    - name: 🚀 Publish (build outputs)
      run: dotnet publish DevHabit.sln --configuration Release --no-restore --no-build --output ./publish
