name: .NET Build and Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: "9.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🛠 Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 🧠 Debug: Print working directory and file tree
        run: |
          echo "Current path: $(pwd)"
          ls -R
        working-directory: ${{ github.workspace }}

      - name: 💾 Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            nuget-${{ runner.os }}-

      - name: 📦 Restore dependencies
        run: dotnet restore DevHabit.sln
        working-directory: ${{ github.workspace }}

      - name: 🧱 Build
        run: dotnet build DevHabit.sln --configuration Release --no-restore
        working-directory: ${{ github.workspace }}

      - name: ✅ Run tests
        run: dotnet test DevHabit.sln --configuration Release --no-restore --no-build --logger trx --results-directory ./TestResults
        working-directory: ${{ github.workspace }}

      - name: 📤 Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./TestResults

      - name: 🚀 Publish (build outputs)
        run: dotnet publish DevHabit.sln --configuration Release --no-restore --no-build --output ./publish
        working-directory: ${{ github.workspace }}
